### ISSUE TITLE
存在生成的bom文件格式错误

### ISSUE THREAD

**Issue by CodMac** [CycloneDX/gh-gomod-generate-sbom#6]
以下几个坐标：
github.com/kubernetes-csi/external-attacher@v3.0.1
github.com/kubernetes-csi/external-resizer@v1.1.0
volcano.sh/volcano@v1.2.0
github.com/volcano-sh/volcano@v1.0.1

生成的bom文件无法通过以下代码校验：
        <dependency>
            <groupId>org.cyclonedx</groupId>
            <artifactId>cyclonedx-core-java</artifactId>
            <version>5.0.1</version>
        </dependency>
-------------
        org.cyclonedx.parsers.JsonParser jsonParser = new org.cyclonedx.parsers.JsonParser();
        jsonParser.isValid(bomFile);
-------------
上面校验会return false， 原因：$.components: the items in the array must be unique
                                                    插件生成的bom文件的components列表存在重复元素

**Comment by nscuro** [comment]
Hi @CodMac,

is it possible to provide the complete BOM you're trying to parse? Please redact internal names if necessary.

Also, what kind of Go project was the BOM generated for? Does the project use vendoring?
